/* DS320-T06-DR: */

CREATE TABLE PRODUTO (
    codigo INTEGER PRIMARY KEY,
    descricao CHARACTER,
    preco DECIMAL,
    FK_FORNECEDOR_codForn INTEGER
);

CREATE TABLE FORNECEDOR (
    codForn INTEGER PRIMARY KEY,
    nome CHARACTER
);

CREATE TABLE NOTAFISCAL (
    numero INTEGER PRIMARY KEY,
    data DATE,
    local CHARACTER,
    FK_Cliente_codigo INTEGER
);

CREATE TABLE Cliente (
    codigo INTEGER PRIMARY KEY,
    nome CHARACTER,
    endereco CHARACTER
);

CREATE TABLE contemItem (
    fk_PRODUTO_codigo INTEGER,
    fk_NOTAFISCAL_numero INTEGER,
    quantidade INTEGER,
    precoUnitario DECIMAL
);
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_2
    FOREIGN KEY (FK_FORNECEDOR_codForn)
    REFERENCES FORNECEDOR (codForn)
    ON DELETE RESTRICT;
 
ALTER TABLE NOTAFISCAL ADD CONSTRAINT FK_NOTAFISCAL_2
    FOREIGN KEY (FK_Cliente_codigo)
    REFERENCES Cliente (codigo)
    ON DELETE RESTRICT;
 
ALTER TABLE contemItem ADD CONSTRAINT FK_contemItem_1
    FOREIGN KEY (fk_PRODUTO_codigo)
    REFERENCES PRODUTO (codigo)
    ON DELETE RESTRICT;
 
ALTER TABLE contemItem ADD CONSTRAINT FK_contemItem_2
    FOREIGN KEY (fk_NOTAFISCAL_numero)
    REFERENCES NOTAFISCAL (numero)
    ON DELETE SET NULL;